# Generated by Django 5.1.2 on 2024-10-27 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='user',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='renewal_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='benefits',
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
