# Generated by Django 5.1.2 on 2024-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_visithistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('ST', 'Standard'), ('PR', 'Premium'), ('VIP', 'VIP')], max_length=50),
        ),
    ]
