# Generated by Django 4.2 on 2024-10-27 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('Musique', 'Musique'), ('Cinema', 'Cinema'), ('Sport', 'Sport')], max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('nbr_participants', models.IntegerField(default=0)),
                ('evt_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2024, 10, 27, 16, 50, 35, 348631))), name='Please check your event date'),
        ),
    ]
