# Generated by Django 4.2 on 2024-10-27 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Please check your event date',
        ),
        migrations.AddField(
            model_name='event',
            name='organisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2024, 10, 27, 19, 0, 35, 588316))), name='Please check your event date'),
        ),
    ]
