# Generated by Django 4.2 on 2024-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_fabrication', models.DateField()),
                ('nom_fabricant', models.CharField(max_length=200)),
                ('mots_cles', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
