# Generated by Django 4.2 on 2024-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expositions/'),
        ),
    ]
