# Generated by Django 4.2 on 2024-10-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_exposition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='autres_champs_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exposition',
            name='autres_champs_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
