# Generated by Django 5.1.2 on 2024-10-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0002_remove_reclamation_reclamation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='user',
        ),
    ]
