# Generated by Django 5.1.2 on 2024-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_remove_reclamation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reclamation_attachments/'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='category',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Billing', 'Billing'), ('Technical', 'Technical'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
